### ISSUE TITLE
Does it support manjaro gnome?

### ISSUE THREAD

**Issue by Yakumo-Yukari** [rbreaves/sorun#21]

**Comment by rbreaves** [comment]
Not yet - there are number of distros I need to slow down and begin work on, but Manjaro is 1 of the top 3 I will be focusing my efforts. Anything based on Ubuntu or Arch/Manjaro are high priorities and thirdly Debian/Fedora.

There is also another repo I need to create for the DE global menu bar switching, Deacon. Deacon will be rolled into Sorun.me. There are really 3 different legitimate methods, technically 4, to implement global menus but I plan to support 3 different global menu bar methods. 2 methods use Vala and one is simply Fildem - for however long it lasts lol. Some will be a combination of methods so that any method will technically have dual monitor support, if needed.

The other one mentioned, but no plans to support is KDE w/ Vala I believe it uses vala too any ways. I just don't plan to really add that one into the mix, KDE users can already pretty easily configure what they want and too the menus and features, while gaining more sane defaults, I suspect may still be a mess and the inconsistent theming situation isn't something I want to delve into.
